config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#welcome'
  resources :cleaning_environments, path: 'limpeza-dos-ambientes', path_names: { new: 'novo', edit: 'editar'}
  resources :environments, path: 'ambientes', path_names: { new: 'novo', edit: 'editar' }
  resources :cleaning_rooms, path: 'limpeza-dos-quartos', path_names: { new: 'novo', edit: 'editar' }
  resources :employees, path: 'funcionarios', path_names: { new: 'novo', edit: 'editar' }
  resources :guests, path: 'hospedes', path_names: { new: 'novo', edit: 'editar' }
  resources :services, path: 'servicos', path_names: { new: 'novo', edit: 'editar' }
  resources :courtesies, path: 'produtos-cortesia', path_names: { new: 'novo', edit: 'editar'}
  resources :rooms, path: 'quartos', path_names: { new: 'novo', edit: 'editar' }
  resources :users, path: 'usuarios', only: [:index, :show, :edit, :update], path_names: { edit: 'editar' }
  resources :meals, path: 'refeicoes', path_names: { new: 'novo', edit: 'editar' }
  resources :bookings, path: 'reservas', path_names: { new: 'novo', edit: 'editar' }
  resources :invoices, path: 'faturas', path_names: { new: 'novo', edit: 'editar' }
  resources :services_uses, path: 'uso-dos-servicos', path_names: { new: 'novo', edit: 'editar' }
  resources :meals_uses, path: 'consumo-das-refeicoes', path_names: { new: 'novo', edit: 'editar' }
  resources :courtesies_uses, path: 'uso-dos-produtos-cortesia', path_names: { new: 'novo', edit: 'editar' }
  resources :environments_uses, path: 'uso-dos-ambientes', path_names: { new: 'novo', edit: 'editar' }
end

app/models/courtesy.rb
class Courtesy < ApplicationRecord
  has_and_belongs_to_many :services
  has_many :courtesies_uses, dependent: :destroy
  
  validates :name, presence: true
  validates :price, presence: true
end

app/controllers/courtesies_controller.rb
class CourtesiesController < ApplicationController
  def index
    @courtesies = Courtesy.all
  end

  def show
    @courtesy = Courtesy.find params[:id]
  end

  def new
    @courtesy = Courtesy.new
  end

  def create
    @courtesy = Courtesy.new courtesy_params

    if @courtesy.save
      flash[:notice] = 'Produto-cortesia criado com sucesso!'
      redirect_to courtesies_path
    else
      render :new
    end
  end

  def edit
    @courtesy = Courtesy.find params[:id]
  end

  def update
    @courtesy = Courtesy.find params[:id]

    if @courtesy.update courtesy_params
      flash[:notice] = 'Produto-cortesia atualizado com sucesso!'
      redirect_to courtesies_path
    else
      render :edit
    end
  end

  def destroy
    @courtesy = Courtesy.find params[:id]
    @courtesy.destroy
    flash[:notice] = 'Produto-cortesia excluído com sucesso!'
    redirect_to courtesies_path
  end

  private

  def courtesy_params
    params.require(:courtesy).permit :name, :description, :price, service_ids: []
  end
end

app/views/courtesies/edit.html.slim
- content_for :page_title, 'Editar Produto-cortesia'

= simple_form_for @courtesy do |f|
  = validation_messages_for @courtesy
  = f.input :name
  = f.input :description
  = f.input :price
  = f.association :services
  = f.button :submit

app/views/courtesies/index.html.slim
- content_for :page_title, 'Lista de Produtos-cortesia'

.box
  .box-body
    table.table.table-striped.table-bordered data-toggle="table"
      thead
        th data-sortable="true" ID
        th data-sortable="true" Nome
        th data-sortable="true" Descrição
        th data-sortable="true" Preço
        th Ações
      tbody
        - @courtesies.each do |courtesy|
          tr
            td = courtesy.id
            td = courtesy.name
            td = courtesy.description
            td = courtesy.price
            td
              = link_to 'Editar', edit_courtesy_path(courtesy), class: 'btn btn-xs btn-primary margin-r-5'
              = link_to 'Visualizar', courtesy_path(courtesy), class: 'btn btn-xs btn-success margin-r-5'
              = link_to 'Excluir', courtesy_path(courtesy), method: :delete, class: 'btn btn-xs btn-danger', data: { confirm: 'Tem certeza que deseja excluir o produto-cortesia?' }

= link_to 'Criar Produto-cortesia', new_courtesy_path, class: 'btn btn-warning'

app/views/courtesies/new.html.slim
- content_for :page_title, 'Criar Produto-cortesia'

= simple_form_for @courtesy do |f|
  = validation_messages_for @courtesy
  = f.input :name
  = f.input :description
  = f.input :price
  = f.association :services
  = f.button :submit

app/views/courtesies/show.html.slim
- content_for :page_title, 'Visualizar Produto-cortesia'

p.margin-bottom
  strong.margin-r-5 ID:
  = @courtesy.id

p.margin-bottom
  strong.margin-r-5 Nome:
  = @courtesy.name

p.margin-bottom
  strong.margin-r-5 Descrição:
  = @courtesy.description

p.margin-bottom
  strong.margin-r-5 Preço:
  = @courtesy.price

p.margin-bottom
  strong.margin-r-5 Serviços:
  ul
    - @courtesy.services.each do |service|
      li
        = service.name

.margin-bottom
  = link_to 'Editar', edit_courtesy_path(@courtesy), class: 'btn btn-xs btn-primary margin-r-5'
  = link_to 'Listar Produtos-cortesia', courtesies_path, class: 'btn btn-xs btn-success margin-r-5'

.nav-tabs-custom
  ul.nav.nav-tabs
    li.active
      a aria-expanded='true' data-toggle='tab' href='#tab-1' Hóspedes que utilizaram produto cortesia hoje
  .tab-content
    #tab-1.tab-pane.active
      table.table.table-striped.table-bordered data-toggle='table'
        thead
          th data-sortable='true' ID
          th data-sortable='true' Nome
          th data-sortable='true' Telefone
          th data-sortable='true' Email
        tbody
          - @courtesy.courtesies_uses.each do |courtesies_use|
            - if courtesies_use.used_at == Date.today
              tr
                td = courtesies_use.booking.guest.id
                td = courtesies_use.booking.guest.name
                td = courtesies_use.booking.guest.phone
                td = courtesies_use.booking.guest.email