config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#welcome'
  resources :cleaning_environments, path: 'limpeza-dos-ambientes', path_names: { new: 'novo', edit: 'editar'}
  resources :environments, path: 'ambientes', path_names: { new: 'novo', edit: 'editar' }
  resources :cleaning_rooms, path: 'limpeza-dos-quartos', path_names: { new: 'novo', edit: 'editar' }
  resources :employees, path: 'funcionarios', path_names: { new: 'novo', edit: 'editar' }
  resources :guests, path: 'hospedes', path_names: { new: 'novo', edit: 'editar' }
  resources :services, path: 'servicos', path_names: { new: 'novo', edit: 'editar' }
  resources :courtesies, path: 'produtos-cortesia', path_names: { new: 'novo', edit: 'editar'}
  resources :rooms, path: 'quartos', path_names: { new: 'novo', edit: 'editar' }
  resources :users, path: 'usuarios', only: [:index, :show, :edit, :update], path_names: { edit: 'editar' }
  resources :meals, path: 'refeicoes', path_names: { new: 'novo', edit: 'editar' }
  resources :bookings, path: 'reservas', path_names: { new: 'novo', edit: 'editar' }
  resources :invoices, path: 'faturas', path_names: { new: 'novo', edit: 'editar' }
  resources :services_uses, path: 'uso-dos-servicos', path_names: { new: 'novo', edit: 'editar' }
  resources :meals_uses, path: 'consumo-das-refeicoes', path_names: { new: 'novo', edit: 'editar' }
  resources :courtesies_uses, path: 'uso-dos-produtos-cortesia', path_names: { new: 'novo', edit: 'editar' }
  resources :environments_uses, path: 'uso-dos-ambientes', path_names: { new: 'novo', edit: 'editar' }
end

app/models/room.rb
class Room < ApplicationRecord
  has_and_belongs_to_many :services
  has_and_belongs_to_many :bookings
  has_many :cleaning_rooms, dependent: :destroy

  validates :number, presence: true, uniqueness: true
  validates :guest_limit, presence: true

  def to_label
    "Quarto: #{number} | #{guest_limit} hóspedes"
  end

  def current_booking
    bookings.select { |booking| Time.now.between?(booking.check_in, booking.check_out) }.first
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.all
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new room_params

    if @room.save
      flash[:notice] = 'Quarto criado com sucesso!'
      redirect_to rooms_path
    else
      render :new
    end
  end

  def show
    @room = Room.find params[:id]
    @current_booking = @room.current_booking
  end

  def edit
    @room = Room.find params[:id]
  end

  def update
    @room = Room.find params[:id]

    if @room.update room_params
      flash[:notice] = 'Quarto atualizado com sucesso!'
      redirect_to rooms_path
    else
      render :edit
    end
  end

  def destroy
    @room = Room.find params[:id]
    @room.destroy
    flash[:notice] = 'Quarto excluído com sucesso!'
    redirect_to rooms_path
  end

  private

  def room_params
    params.require(:room).permit :number, :guest_limit, service_ids: []
  end
end

app/views/rooms/edit.html.slim
- content_for :page_title, 'Editar Quarto'

= simple_form_for @room do |f|
  = validation_messages_for @room
  = f.input :number
  = f.input :guest_limit
  = f.association :services
  = f.button :submit

app/views/rooms/index.html.slim
- content_for :page_title, 'Lista de Quartos'

.box
  .box-body
    table.table.table-striped.table-bordered data-toggle="table"
      thead
        th data-sortable="true" ID
        th data-sortable="true" Número
        th data-sortable="true" Limite de Hóspedes
        th Ações
      tbody
        - @rooms.each do |room|
          tr
            td = room.id
            td = room.number
            td = room.guest_limit
            td
              = link_to 'Editar', edit_room_path(room), class: 'btn btn-xs btn-primary margin-r-5'
              = link_to 'Visualizar', room_path(room), class: 'btn btn-xs btn-success margin-r-5'
              = link_to 'Excluir', room_path(room), method: :delete, class: 'btn btn-xs btn-danger', data: { confirm: 'Tem certeza que deseja excluir o quarto?' }

= link_to 'Criar Quarto', new_room_path, class: 'btn btn-warning'

app/views/rooms/new.html.slim
- content_for :page_title, 'Criar Quarto'

= simple_form_for @room do |f|
  = validation_messages_for @room
  = f.input :number
  = f.input :guest_limit
  = f.association :services
  = f.button :submit

app/views/rooms/show.html.slim
- content_for :page_title, 'Visualizar Quarto'

p.margin-bottom
  strong.margin-r-5 ID:
  = @room.id

p.margin-bottom
  strong.margin-r-5 Número:
  = @room.number

p.margin-bottom
  strong.margin-r-5 Limite de Hóspedes:
  = @room.guest_limit

p.margin-bottom
  strong.margin-r-5 Serviços:
  ul
    - @room.services.each do |service|
      li
        = service.name

.margin-bottom
  = link_to 'Editar', edit_room_path(@room), class: 'btn btn-xs btn-primary margin-r-5'
  = link_to 'Listar Quartos', rooms_path, class: 'btn btn-xs btn-success margin-r-5'

.nav-tabs-custom
  ul.nav.nav-tabs
    li.active
      a aria-expanded='true' data-toggle='tab' href='#tab-1' Limpeza de Quarto
    li
      a data-toggle='tab' href='#tab-2' Reserva atual
  .tab-content
    #tab-1.tab-pane.active
      table.table.table-striped.table-bordered data-toggle='table'
        thead
          th data-sortable='true' ID
          th data-sortable='true' Data da Limpeza
        tbody
          - @room.cleaning_rooms.each do |cleaning_room|
            tr
              td = cleaning_room.id
              td = I18n.l cleaning_room.cleaning_date
    #tab-2.tab-pane
      - if @current_booking
        p.margin-bottom
          strong.margin-r-5 ID:
          = @current_booking.id

        p.margin-bottom
          strong.margin-r-5 Check-in:
          = l @current_booking.check_in

        p.margin-bottom
          strong.margin-r-5 Check-out:
          = l @current_booking.check_out

        p.margin-bottom
          strong.margin-r-5 Quartos:
          = @current_booking.rooms.map(&:number).join(', ')

        p.margin-bottom
          strong.margin-r-5 Hóspede:
          = @current_booking.guest.name

        p.margin-bottom
          strong.margin-r-5 Acompanhantes:
          = @current_booking.companions
      - else
        p.margin-bottom
          .margin-r-5 Quarto não possui reserva na data atual.