config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'home#welcome'
  resources :cleaning_environments, path: 'limpeza-dos-ambientes', path_names: { new: 'novo', edit: 'editar'}
  resources :environments, path: 'ambientes', path_names: { new: 'novo', edit: 'editar' }
  resources :cleaning_rooms, path: 'limpeza-dos-quartos', path_names: { new: 'novo', edit: 'editar' }
  resources :employees, path: 'funcionarios', path_names: { new: 'novo', edit: 'editar' }
  resources :guests, path: 'hospedes', path_names: { new: 'novo', edit: 'editar' }
  resources :services, path: 'servicos', path_names: { new: 'novo', edit: 'editar' }
  resources :courtesies, path: 'produtos-cortesia', path_names: { new: 'novo', edit: 'editar'}
  resources :rooms, path: 'quartos', path_names: { new: 'novo', edit: 'editar' }
  resources :users, path: 'usuarios', only: [:index, :show, :edit, :update], path_names: { edit: 'editar' }
  resources :meals, path: 'refeicoes', path_names: { new: 'novo', edit: 'editar' }
  resources :bookings, path: 'reservas', path_names: { new: 'novo', edit: 'editar' }
  resources :invoices, path: 'faturas', path_names: { new: 'novo', edit: 'editar' }
  resources :services_uses, path: 'uso-dos-servicos', path_names: { new: 'novo', edit: 'editar' }
  resources :meals_uses, path: 'consumo-das-refeicoes', path_names: { new: 'novo', edit: 'editar' }
  resources :courtesies_uses, path: 'uso-dos-produtos-cortesia', path_names: { new: 'novo', edit: 'editar' }
  resources :environments_uses, path: 'uso-dos-ambientes', path_names: { new: 'novo', edit: 'editar' }
end

app/models/environment.rb
class Environment < ApplicationRecord
  has_many :cleaning_environments, dependent: :destroy
  has_many :environments_uses, dependent: :destroy

  validates :name, presence: true
  validates :price, presence: true
end

app/controllers/environments_controller.rb
class EnvironmentsController < ApplicationController
  def index
    @environments = Environment.all
  end

  def show
    @environment = Environment.find params[:id]
  end

  def new
    @environment = Environment.new
  end

  def edit
    @environment = Environment.find params[:id]
  end

  def create
    @environment = Environment.new environment_params

    if @environment.save
      flash[:notice] = 'Ambiente criado com sucesso!'
      redirect_to environments_path
    else
      render :new
    end
  end

  def update
    @environment = Environment.find params[:id]

    if @environment.update environment_params
      flash[:notice] = 'Ambiente atualizado com sucesso!'
      redirect_to environments_path
    else
      render :edit
    end
  end

  def destroy
    @environment = Environment.find params[:id]
    @environment.destroy
    flash[:notice] = 'Ambiente excluído com sucesso!'
    redirect_to environments_path
  end

  private

  def environment_params
    params.require(:environment).permit :name, :description, :price
  end
end

app/views/environments/edit.html.slim
- content_for :page_title, 'Editar Ambiente'

= simple_form_for @environment do |f|
  = validation_messages_for @environment
  = f.input :name
  = f.input :description
  = f.input :price
  = f.button :submit

app/views/environments/index.html.slim
- content_for :page_title, 'Lista de Ambientes'

.box
  .box-body
    table.table.table-striped.table-bordered data-toggle="table"
      thead
        th data-sortable="true" ID
        th data-sortable="true" Nome
        th data-sortable="true" Descrição
        th data-sortable="true" Preço
        th Ações
      tbody
        - @environments.each do |environment|
          tr
            td = environment.id
            td = environment.name
            td = environment.description
            td = environment.price
            td
              = link_to 'Editar', edit_environment_path(environment), class: 'btn btn-xs btn-primary margin-r-5'
              = link_to 'Visualizar', environment_path(environment), class: 'btn btn-xs btn-success margin-r-5'
              = link_to 'Excluir', environment_path(environment), method: :delete, class: 'btn btn-xs btn-danger', data: { confirm: 'Tem certeza que deseja excluir o ambiente?' }

= link_to 'Criar Ambiente', new_environment_path, class: 'btn btn-warning'

app/views/environments/new.html.slim
- content_for :page_title, 'Criar Ambiente'

= simple_form_for @environment do |f|
  = validation_messages_for @environment
  = f.input :name
  = f.input :description
  = f.input :price
  = f.button :submit

app/views/environments/show.html.slim
- content_for :page_title, 'Visualizar Ambiente'

p.margin-bottom
  strong.margin-r-5 ID:
  = @environment.id

p.margin-bottom
  strong.margin-r-5 Nome:
  = @environment.name

p.margin-bottom
  strong.margin-r-5 Descrição:
  = @environment.description

p.margin-bottom
  strong.margin-r-5 Preço:
  = @environment.price

.margin-bottom
  = link_to 'Editar', edit_environment_path(@environment), class: 'btn btn-xs btn-primary margin-r-5'
  = link_to 'Listar Ambientes', environments_path, class: 'btn btn-xs btn-success margin-r-5'

.nav-tabs-custom
  ul.nav.nav-tabs
    li.active
      a aria-expanded='true' data-toggle='tab' href='#tab-1' Hóspedes que utilizaram hoje
    li
      a aria-expanded='true' data-toggle='tab' href='#tab-2' Limpeza de Ambiente
  .tab-content
    #tab-1.tab-pane.active
      table.table.table-striped.table-bordered data-toggle='table'
        thead
          th data-sortable='true' ID
          th data-sortable='true' Nome
          th data-sortable='true' Telefone
          th data-sortable='true' Email
        tbody
          - @environment.environments_uses.where(used_at: Date.today).each do |environments_use|
            tr
              td = environments_use.booking.guest.id
              td = environments_use.booking.guest.name
              td = environments_use.booking.guest.phone
              td = environments_use.booking.guest.email
    #tab-2.tab-pane
      table.table.table-striped.table-bordered data-toggle='table'
        thead
          th data-sortable='true' Data da Limpeza
        tbody
          - @environment.cleaning_environments.each do |cleaning_environment|
            tr
              td = cleaning_environment.id
              td = I18n.l cleaning_environment.cleaning_date